site_name: maplibre-gl-three
site_description: Brings Three.js capabilities into MapLibre GL JS
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/safwat-halaby/maplibre-gl-three
docs_dir: docs
site_dir: site
exclude_docs: |
  /requirements.*

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - fenced_code
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Features & limitations: features.md
  - Changelog: changelog.md
  - License: https://github.com/safwat-halaby/maplibre-gl-three/blob/master/LICENSE.txt
  - Examples and demos:
    - Live Demos: examples/live.md
    - Repository examples: examples/repo.md
  - Principles:
    - Core principles: principles.md 
    - Coordinate systems and projections: coordinate-systems.md
  - API Reference:
    - Main classes and interfaces: api-quick.md
    - Full API Reference: api/index.md
  - Development:
    - Development: development.md
