site_name: maplibre-gl-three
site_description: Brings Three.js capabilities into MapLibre GL JS
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/safwat-halaby/maplibre-gl-three
docs_dir: docs
site_dir: site
exclude_docs: |
  /requirements.*

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - fenced_code
  - toc:
      permalink: true

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Features & Limitations: features.md
  - Usage Guide:
    - Getting started: getting-started.md
    - Frequently Asked Questions: faq.md
  - Examples and demos:
    - Live Demos: examples/live.md
    - Repository Examples: examples/repo.md
  - Principles:
    - Core principles: principles.md 
    - Coordinate Systems and Projections: coordinate-systems.md
  - Other:
    - Changelog: changelog.md
    - Development: development.md
    - License: license.md
  - API:
    - API Reference: api/index.md
    - External API references: external.md
